name: entailment-tda
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs
  - aiohttp
  - aiosignal
  - arrow-cpp
  - async-timeout
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - blas
  - boost-cpp
  - bottleneck
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - charset-normalizer
  - colorama
  - contourpy
  - cycler
  - datasets
  - deprecated
  - dill
  - expat
  - filelock
  - fonttools
  - freetype
  - frozenlist
  - fsspec
  - gflags
  - glog
  - gmp
  - gmpy2
  - hopcroftkarp
  - huggingface_hub
  - icu
  - idna
  - intel-openmp
  - jinja2
  - joblib
  - jpeg
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libabseil
  - libblas
  - libboost
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libevent
  - libffi
  - libgfortran
  - libgfortran5
  - libgrpc
  - libiconv
  - libjpeg-turbo
  - liblapack
  - libllvm14
  - libnghttp2
  - libpng
  - libprotobuf
  - libre2-11
  - libsqlite
  - libssh2
  - libthrift
  - libtiff
  - libutf8proc
  - libwebp-base
  - libzlib
  - llvm-openmp
  - llvmlite
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - mpmath
  - multidict
  - multiprocess
  - munkres
  - narwhals
  - ncurses
  - networkx
  - numba
  - numexpr
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg
  - openssl
  - orc
  - packaging
  - pandas
  - patsy
  - persim
  - pillow
  - pip
  - plotly
  - propcache
  - pyarrow
  - pybind11-abi
  - pynndescent
  - pyparsing
  - pysocks
  - python=3.10.18
  - python-dateutil
  - python-tzdata
  - python-xxhash
  - python_abi
  - pytorch
  - pytorch-mutex
  - pytz
  - pyyaml
  - qhull
  - re2
  - readline
  - regex
  - requests
  - ripser
  - safetensors
  - scipy
  - seaborn
  - seaborn-base
  - setuptools
  - six
  - snappy
  - sqlite
  - statsmodels
  - sympy
  - tbb
  - threadpoolctl
  - tk
  - tokenizers
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - transformers
  - typing-extensions
  - tzdata
  - umap-learn
  - unicodedata2
  - urllib3
  - utf8proc
  - wheel
  - wrapt
  - xxhash
  - xz
  - yaml
  - yarl
  - zlib
  - zstd
  - pip:
      - asttokens
      - comm
      - cython
      - decorator
      - exceptiongroup
      - executing
      - geoopt
      - giotto-ph
      - giotto-tda
      - igraph
      - ipython
      - ipywidgets
      - jedi
      - jupyterlab-widgets
      - kmapper
      - matplotlib-inline
      - parso
      - pexpect
      - prompt-toolkit
      - ptyprocess
      - pure-eval
      - pyflagser
      - pygments
      - scikit-learn
      - scikit-tda
      - stack-data
      - tadasets
      - texttable
      - traitlets
      - wcwidth
      - widgetsnbextension
