name: /vol/bitbucket/ahb24/tda_entailment_new
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.13
  - aiosignal=1.3.2
  - arrow-cpp=13.0.0
  - async-timeout=5.0.1
  - attr=2.5.1
  - attrs=25.3.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - blas=1.0
  - blas-devel=3.9.0
  - boost-cpp=1.85.0
  - bottleneck=1.5.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.6.15
  - certifi=2025.7.14
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - contourpy=1.3.2
  - cpython=3.10.18
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - datasets=2.19.2
  - dbus=1.13.18
  - deprecated=1.2.18
  - dill=0.3.8
  - expat=2.7.1
  - ffmpeg=4.3
  - filelock=3.18.0
  - fontconfig=2.14.1
  - fonttools=4.58.4
  - freetype=2.13.3
  - frozenlist=1.6.0
  - fsspec=2024.3.1
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - gflags=2.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - h2=4.2.0
  - hf-xet=1.1.4
  - hopcroftkarp=1.2.4
  - hpack=4.1.0
  - huggingface_hub=0.33.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - joblib=1.5.1
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=13.0.0
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libblas=3.9.0
  - libboost=1.85.0
  - libboost-devel=1.85.0
  - libboost-headers=1.85.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcups=2.3.3
  - libcurand=10.3.5.147
  - libcurl=8.12.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libcxx=20.1.7
  - libcxxabi=20.1.7
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.78.4
  - libgomp=15.1.0
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgpg-error=1.55
  - libgrpc=1.62.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.58.0
  - libnl=3.11.0
  - libnpp=12.2.5.30
  - libntlm=1.8
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.43
  - libpq=17.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=256.9
  - libtasn1=4.19.0
  - libthrift=0.19.0
  - libtiff=4.7.0
  - libudev1=257.4
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=1.41.5
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libxslt=1.1.41
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - llvmlite=0.42.0
  - loguru=0.7.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - minizip=4.0.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.4.4
  - multiprocess=0.70.17
  - munkres=1.1.4
  - mysql=8.4.0
  - narwhals=1.43.0
  - ncurses=6.5
  - nettle=3.7.3
  - networkx=3.4.2
  - ninja=1.12.1
  - ninja-base=1.12.1
  - nomkl=3.0
  - nspr=4.36
  - nss=3.100
  - numba=0.59.1
  - numexpr=2.10.2
  - numpy=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.5
  - openssl=3.5.0
  - orc=2.0.1
  - packaging=25.0
  - pandas=2.3.0
  - patsy=1.0.1
  - pcre2=10.42
  - persim=0.3.8
  - pillow=11.1.0
  - pip=25.1.1
  - platformdirs=4.3.7
  - plotly=6.1.2
  - pooch=1.8.2
  - propcache=0.3.1
  - pthread-stubs=0.3
  - pyarrow=13.0.0
  - pyarrow-hotfix=0.7
  - pybind11-abi=4
  - pycparser=2.22
  - pynndescent=0.5.13
  - pyparsing=3.2.3
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-gil=3.10.18
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtshadertools=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebengine=6.7.3
  - qtwebsockets=6.7.3
  - rdma-core=55.0
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.4
  - ripser=0.6.12
  - s2n=1.4.15
  - safetensors=0.5.3
  - scipy=1.10.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.46.0
  - statsmodels=0.14.4
  - sympy=1.14.0
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.14
  - tokenizers=0.21.1
  - torchaudio=2.4.1
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - transformers=4.52.4
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - tzdata=2025b
  - ucx=1.16.0
  - umap-learn=0.5.7
  - unicodedata2=16.0.0
  - urllib3=2.4.0
  - utf8proc=2.6.1
  - wheel=0.45.1
  - wrapt=1.17.2
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-renderutil=0.3.10
  - xkeyboard-config=2.45
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xxhash=0.8.3
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.1
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - asttokens==3.0.0
      - comm==0.2.2
      - cython==3.1.2
      - decorator==5.2.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - geoopt==0.5.0
      - giotto-ph==0.2.4
      - giotto-tda==0.6.2
      - gudhi==3.11.0
      - hdbscan==0.8.40
      - igraph==0.11.9
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - jedi==0.19.2
      - jupyterlab-widgets==3.0.15
      - kmapper==2.1.0
      - matplotlib-inline==0.1.7
      - parso==0.8.4
      - pexpect==4.9.0
      - pot==0.8.2
      - prompt-toolkit==3.0.51
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyflagser==0.4.7
      - pygments==2.19.1
      - scikit-learn==1.3.2
      - scikit-tda==1.1.1
      - stack-data==0.6.3
      - tadasets==0.2.1
      - texttable==1.7.0
      - torch-topological==0.1.7
      - torchph==0.1.1
      - traitlets==5.14.3
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.14
